export type ConnectorDetailsTranslation = {
    page_title: string,
    back_to_connectors: string,
    not_in_use: string,
    delete_connector: string,
    deletion_reminder: string,
    deleted: string,
    settings_tab: string,
    configuration_tab: string,
    disable_connector: string,
    activate_connector: string,
    connector_disabled: string,
    connector_activated: string,
    activate_action: string,
    disable_action: string,
    activate_connector_reminder: string,
    disable_connector_reminder: string,
    settings: {
        settings: string,
        settings_description: string,
        name: string,
        form_title: string,
        form_description: string,
    },
    configuration: {
        configuration: string,
        configuration_description: string,
        name: string,
        form_title: string,
        form_description: string,
    }
}